import React, { useState, useMemo } from 'react';
import {
  ChevronLeft,
  ChevronRight,
  Download,
  Printer,
  Plus,
  Trash2,
  Edit2,
  RotateCcw,
  Sparkles,
  Save,
  Calendar,
  AlertCircle
} from 'lucide-react';
import { SchoolConfig, PpctItem, TimetableSlot, LessonPlanRow } from '../types';
import { getWeekDateRange, getDateForDayOfWeek, getDayOfWeekName } from '../utils/dateUtils';
import { exportLessonPlanToDocx } from '../utils/docxExport';
import { LessonDetailModal } from './LessonDetailModal';

interface DocumentPreviewProps {
  config: SchoolConfig;
  ppctList: PpctItem[];
  timetable: TimetableSlot[];
  customizedWeeks: Record<number, LessonPlanRow[]>;
  onSaveWeekRows: (weekNumber: number, rows: LessonPlanRow[]) => void;
  onResetWeekRows: (weekNumber: number) => void;
  onUpdateConfig?: (config: SchoolConfig) => void;
  teacherType?: 'GVCN' | 'GVBM';
}

export const DocumentPreview: React.FC<DocumentPreviewProps> = ({
  config,
  ppctList,
  timetable,
  customizedWeeks,
  onSaveWeekRows,
  onResetWeekRows,
  onUpdateConfig,
  teacherType = 'GVCN'
}) => {
  const [currentWeek, setCurrentWeek] = useState<number>(1);
  const [displayFontSize, setDisplayFontSize] = useState<number>(12); // Default font size 12
  const [editingRow, setEditingRow] = useState<LessonPlanRow | null>(null);
  const [isExporting, setIsExporting] = useState<boolean>(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => {
      setToastMessage(null);
    }, 3000);
  };
  const [isWeekDateModalOpen, setIsWeekDateModalOpen] = useState<boolean>(false);
  const [overrideDateInput, setOverrideDateInput] = useState<string>('');

  const hasDirectOverride = Boolean(config.weekStartOverrides?.[currentWeek]);
  const precedingOverrideWeeks = useMemo(() => {
    if (!config.weekStartOverrides) return [];
    return Object.keys(config.weekStartOverrides)
      .map(Number)
      .filter((w) => !isNaN(w) && w < currentWeek && Boolean(config.weekStartOverrides![w]))
      .sort((a, b) => b - a);
  }, [config.weekStartOverrides, currentWeek]);

  const inheritedBaseWeek = precedingOverrideWeeks.length > 0 ? precedingOverrideWeeks[0] : null;

  const handleOpenWeekDateModal = () => {
    const currentMonday = weekDates.mondayDate;
    const yyyy = currentMonday.getFullYear();
    const mm = String(currentMonday.getMonth() + 1).padStart(2, '0');
    const dd = String(currentMonday.getDate()).padStart(2, '0');
    setOverrideDateInput(`${yyyy}-${mm}-${dd}`);
    setIsWeekDateModalOpen(true);
  };

  const handleSaveWeekDateOverride = (e: React.FormEvent) => {
    e.preventDefault();
    if (!overrideDateInput) return;

    const existingOverrides = config.weekStartOverrides || {};
    const updatedOverrides = {
      ...existingOverrides,
      [currentWeek]: overrideDateInput
    };

    const updatedConfig = {
      ...config,
      weekStartOverrides: updatedOverrides
    };

    if (onUpdateConfig) {
      onUpdateConfig(updatedConfig);
    }
    setIsWeekDateModalOpen(false);
    showToast(`Đã lưu mốc ngày bắt đầu Tuần ${currentWeek}! Các tuần tiếp theo tự động nối tiếp.`);
  };

  const handleClearWeekDateOverride = () => {
    const existingOverrides = { ...(config.weekStartOverrides || {}) };
    delete existingOverrides[currentWeek];

    const updatedConfig = {
      ...config,
      weekStartOverrides: existingOverrides
    };

    if (onUpdateConfig) {
      onUpdateConfig(updatedConfig);
    }
    setIsWeekDateModalOpen(false);
    showToast(`Đã xóa mốc tùy chỉnh Tuần ${currentWeek}! Tự động tính theo chuỗi.`);
  };

  // Tính khoảng ngày của tuần hiện tại (kèm mốc tùy chỉnh nghỉ Tết / lễ nếu có)
  const weekDates = useMemo(() => {
    return getWeekDateRange(config.startDateWeek1 || '2024-09-09', currentWeek, config.weekStartOverrides);
  }, [config.startDateWeek1, config.weekStartOverrides, currentWeek]);

  // Tự động sinh danh sách tiết dạy từ Thời Khóa Biểu và PPCT cho tuần hiện tại
  const autoGeneratedRows: LessonPlanRow[] = useMemo(() => {
    // Sắp xếp TKB: Thứ (2->7), Buổi (morning trước afternoon), Tiết (1->5)
    const sortedSlots = [...timetable].sort((a, b) => {
      if (a.dayOfWeek !== b.dayOfWeek) return a.dayOfWeek - b.dayOfWeek;
      const sessionScore = (s: string) => (s === 'morning' || s === 'Sáng' ? 0 : 1);
      if (sessionScore(a.session) !== sessionScore(b.session)) {
        return sessionScore(a.session) - sessionScore(b.session);
      }
      return a.period - b.period;
    });

    // Hàm tự động nhận dạng Khối lớp từ slot.grade hoặc từ tên lớp (VD: "3A1" -> Khối 3, "4A2" -> Khối 4)
    const detectGrade = (slotGrade?: number | string, classNameStr?: string): number => {
      if (slotGrade && Number(slotGrade) > 0) return Number(slotGrade);
      if (classNameStr) {
        const match = classNameStr.match(/\d+/);
        if (match) return parseInt(match[0], 10);
      }
      return 0;
    };

    // Helper kiểm tra khớp mờ Phân môn
    const isSubMatch = (pSub?: string, slotSub?: string): boolean => {
      if (!pSub && !slotSub) return true;
      if (!pSub || !slotSub) return true;
      const a = pSub.trim().toLowerCase();
      const b = slotSub.trim().toLowerCase();
      if (a === b) return true;
      if (a.includes(b) || b.includes(a)) return true;

      // Key aliases
      if ((a.includes('đọc') || a.includes('tập đọc')) && (b.includes('đọc') || b.includes('tập đọc'))) return true;
      if ((a.includes('ltvc') || a.includes('từ và câu')) && (b.includes('ltvc') || b.includes('từ và câu'))) return true;
      if ((a.includes('viết') || a.includes('tập làm văn') || a.includes('chính tả')) && (b.includes('viết') || b.includes('tập làm văn') || b.includes('chính tả'))) return true;
      if ((a.includes('nói') || a.includes('nghe')) && (b.includes('nói') || b.includes('nghe'))) return true;
      if (a.includes('lịch sử') && b.includes('lịch sử')) return true;
      if (a.includes('địa lí') && b.includes('địa lí')) return true;
      if (a.includes('âm nhạc') && b.includes('âm nhạc')) return true;
      if (a.includes('mĩ thuật') && b.includes('mĩ thuật')) return true;
      if (a.includes('chào cờ') && b.includes('chào cờ')) return true;
      if (a.includes('sinh hoạt lớp') && b.includes('sinh hoạt lớp')) return true;
      if (a.includes('chủ đề') && b.includes('chủ đề')) return true;

      return false;
    };

    // Helper kiểm tra khớp Tên môn học
    const isSubjectMatch = (pSubj: string, slotSubj: string): boolean => {
      const a = pSubj.trim().toLowerCase();
      const b = slotSubj.trim().toLowerCase();
      if (a === b) return true;
      if (a.includes(b) || b.includes(a)) return true;
      if ((a.includes('tiếng việt') || a.includes('tv')) && (b.includes('tiếng việt') || b.includes('tv'))) return true;
      if ((a.includes('lịch sử') || a.includes('địa lí')) && (b.includes('lịch sử') || b.includes('địa lí'))) return true;
      if ((a.includes('trải nghiệm') || a.includes('hđtn')) && (b.includes('trải nghiệm') || b.includes('hđtn'))) return true;
      if ((a.includes('tự nhiên') || a.includes('tnxh')) && (b.includes('tự nhiên') || b.includes('tnxh'))) return true;
      return false;
    };

    // Theo dõi số tiết đã dạy của từng khối/môn trong tuần
    const subjectOccurrences: Record<string, number> = {};

    return sortedSlots.map((slot, index) => {
      const classGrade = detectGrade(slot.grade, slot.className);
      const cleanSlotSubj = (slot.subject || '').trim();
      const cleanSlotSubSubject = (slot.subSubject || '').trim();
      const key = `${classGrade}_${cleanSlotSubj.toLowerCase()}_${cleanSlotSubSubject.toLowerCase()}`;
      const count = (subjectOccurrences[key] || 0) + 1;
      subjectOccurrences[key] = count;

      // 1. Lọc tất cả bài dạy PPCT cho tuần hiện tại
      const ppctForWeek = ppctList.filter((p) => Number(p.week) === currentWeek);

      // 2. Lọc theo Khối (nếu có khối)
      const ppctGradeAndWeek = classGrade > 0
        ? ppctForWeek.filter((p) => Number(p.grade) === classGrade)
        : ppctForWeek;

      // 3. Tìm bài dạy khớp Tên môn & Phân môn
      let matchingPpctList = (ppctGradeAndWeek.length > 0 ? ppctGradeAndWeek : ppctForWeek).filter(
        (p) =>
          isSubjectMatch(p.subject, cleanSlotSubj) &&
          isSubMatch(p.subSubject, cleanSlotSubSubject)
      );

      // 4. Nếu chưa tìm thấy, nới lỏng tìm theo Tên môn
      if (matchingPpctList.length === 0) {
        matchingPpctList = (ppctGradeAndWeek.length > 0 ? ppctGradeAndWeek : ppctForWeek).filter(
          (p) => isSubjectMatch(p.subject, cleanSlotSubj)
        );
      }

      // 5. Chọn tiết thứ `count` trong danh sách các bài dạy phù hợp
      let matchingPpct = matchingPpctList.find((p) => Number(p.periodIndex) === count)
        || matchingPpctList[count - 1]
        || matchingPpctList[0];

      // 6. Nếu vẫn chưa có, khớp mờ trên toàn danh sách PPCT cho tuần này
      if (!matchingPpct && cleanSlotSubj) {
        matchingPpct = ppctList.find(
          (p) =>
            isSubjectMatch(p.subject, cleanSlotSubj) &&
            isSubMatch(p.subSubject, cleanSlotSubSubject) &&
            Number(p.week) === currentWeek
        );
      }

      const dateStr = getDateForDayOfWeek(
        config.startDateWeek1 || '2024-09-09',
        currentWeek,
        slot.dayOfWeek,
        config.weekStartOverrides
      );

      // Nhận dạng tên bài học mặc định thông minh nếu không tìm thấy trong PPCT
      const subSubjectLabel = slot.subSubject || matchingPpct?.subSubject || '';
      let defaultLessonName = `Bài dạy Môn ${slot.subject}${subSubjectLabel ? ` (${subSubjectLabel})` : ''} (Tuần ${currentWeek})`;
      const lowerSubj = cleanSlotSubj.toLowerCase();
      if (lowerSubj.includes('chào cờ') || subSubjectLabel.toLowerCase().includes('chào cờ')) {
        defaultLessonName = 'Chào cờ đầu tuần';
      } else if (lowerSubj.includes('sinh hoạt lớp') || lowerSubj === 'shl' || subSubjectLabel.toLowerCase().includes('sinh hoạt lớp')) {
        defaultLessonName = 'Sinh hoạt lớp cuối tuần';
      } else if (lowerSubj.includes('hoạt động trải nghiệm') || lowerSubj === 'hđtn') {
        defaultLessonName = subSubjectLabel ? `HĐTN - ${subSubjectLabel} (Tuần ${currentWeek})` : `Hoạt động trải nghiệm - Tuần ${currentWeek}`;
      } else if (classGrade > 0) {
        defaultLessonName = `Bài dạy Khối ${classGrade}${subSubjectLabel ? ` - ${subSubjectLabel}` : ''} (Tuần ${currentWeek})`;
      }

      // Giữ tên môn học gốc nguyên bản (ví dụ: Tiếng Việt, Toán, Lịch sử và Địa lí)
      const pureSubject = slot.subject ? slot.subject.split(' (')[0].trim() : 'Môn học';

      return {
        id: `row-${currentWeek}-${slot.id || index}`,
        dayOfWeek: slot.dayOfWeek,
        dateStr,
        session: slot.session === 'morning' || slot.session === 'Sáng' ? 'Sáng' : 'Chiều',
        period: slot.period,
        className: slot.className,
        subject: pureSubject,
        subSubject: slot.subSubject || matchingPpct?.subSubject || '',
        lessonName: matchingPpct?.lessonName || defaultLessonName,
        integrationNote: matchingPpct?.integrationNote || '',
        isCustomized: false
      };
    });
  }, [timetable, ppctList, currentWeek, config.startDateWeek1]);

  // Hàng hiển thị: TỰ ĐỘNG ĐỒNG BỘ TRỰC TIẾP TỪ PPCT & TKB MỚI NHẤT
  // Hệ thống tự động cập nhật tên bài dạy ngay khi TKB/PPCT thay đổi mà người dùng KHÔNG CẦN bấm nút
  const displayRows: LessonPlanRow[] = useMemo(() => {
    const savedCustoms = customizedWeeks[currentWeek];
    if (!savedCustoms || savedCustoms.length === 0) {
      return autoGeneratedRows;
    }

    return autoGeneratedRows.map((autoRow) => {
      const customMatch = savedCustoms.find(
        (c) =>
          c.id === autoRow.id ||
          (c.dayOfWeek === autoRow.dayOfWeek &&
           c.session === autoRow.session &&
           c.period === autoRow.period &&
           c.className === autoRow.className)
      );

      if (!customMatch || !customMatch.isCustomized) {
        return autoRow;
      }

      return {
        ...autoRow,
        lessonName: customMatch.lessonName || autoRow.lessonName,
        subSubject: customMatch.subSubject || autoRow.subSubject,
        integrationNote: customMatch.integrationNote !== undefined ? customMatch.integrationNote : autoRow.integrationNote,
        isCustomized: true
      };
    });
  }, [customizedWeeks, currentWeek, autoGeneratedRows]);

  // Sắp xếp hàng chuẩn theo: Thứ (2 -> 7) -> Buổi (Sáng -> Chiều) -> Tiết (1 -> 5)
  const sortedDisplayRows = useMemo(() => {
    return [...displayRows].sort((a, b) => {
      if (a.dayOfWeek !== b.dayOfWeek) return a.dayOfWeek - b.dayOfWeek;
      const sessionOrder = (s: string) => (s === 'Sáng' || s === 'morning' ? 1 : 2);
      if (sessionOrder(a.session) !== sessionOrder(b.session)) {
        return sessionOrder(a.session) - sessionOrder(b.session);
      }
      return a.period - b.period;
    });
  }, [displayRows]);

  const homeClassName = useMemo(() => {
    const rowCls = sortedDisplayRows.find((r) => r.className && r.className !== 'Chào cờ' && r.className !== 'Sinh hoạt lớp')?.className;
    if (rowCls) return rowCls;
    const ttCls = timetable.find((s) => s.className && s.className !== 'Chào cờ' && s.className !== 'Sinh hoạt lớp')?.className;
    if (ttCls) return ttCls;
    return '3A1';
  }, [sortedDisplayRows, timetable]);

  // Tự động điều chỉnh khoảng cách dòng (padding) để nội dung tự co giãn vừa đẹp trên trang A4
  const dynamicCellPy = useMemo(() => {
    const total = sortedDisplayRows.length;
    if (total <= 10) return 'py-2.5';
    if (total <= 14) return 'py-1.5';
    if (total <= 18) return 'py-1';
    return 'py-0.5';
  }, [sortedDisplayRows.length]);

  // Helper lấy tên môn học chính nguyên bản
  const getPureSubject = (s: string) => (s || '').split(' (')[0].trim();

  // Tính toán gộp ô (rowSpan) cho Thứ, Buổi và Môn học chính
  const rowSpanData = useMemo(() => {
    const list = sortedDisplayRows;
    return list.map((row, idx) => {
      const isFirstOfDay = idx === 0 || row.dayOfWeek !== list[idx - 1].dayOfWeek;
      let daySpan = 0;
      if (isFirstOfDay) {
        let count = 0;
        for (let i = idx; i < list.length && list[i].dayOfWeek === row.dayOfWeek; i++) {
          count++;
        }
        daySpan = count;
      }

      const isFirstOfSession =
        isFirstOfDay || row.session !== list[idx - 1].session;
      let sessionSpan = 0;
      if (isFirstOfSession) {
        let count = 0;
        for (
          let i = idx;
          i < list.length &&
          list[i].dayOfWeek === row.dayOfWeek &&
          list[i].session === row.session;
          i++
        ) {
          count++;
        }
        sessionSpan = count;
      }

      const isFirstOfSubject =
        isFirstOfSession ||
        getPureSubject(row.subject) !== getPureSubject(list[idx - 1].subject);

      let subjectSpan = 0;
      if (isFirstOfSubject) {
        let count = 0;
        for (
          let i = idx;
          i < list.length &&
          list[i].dayOfWeek === row.dayOfWeek &&
          list[i].session === row.session &&
          getPureSubject(list[i].subject) === getPureSubject(row.subject);
          i++
        ) {
          count++;
        }
        subjectSpan = count;
      }

      return {
        row,
        daySpan,
        sessionSpan,
        subjectSpan
      };
    });
  }, [sortedDisplayRows]);

  const handleUpdateRow = (updatedRow: LessonPlanRow) => {
    const newRows = displayRows.map((r) => (r.id === updatedRow.id ? updatedRow : r));
    onSaveWeekRows(currentWeek, newRows);
    showToast('Đã cập nhật nội dung tiết dạy!');
  };

  const handleInlineChange = (id: string, field: keyof LessonPlanRow, value: string) => {
    const newRows = displayRows.map((r) => {
      if (r.id === id) {
        return {
          ...r,
          [field]: value,
          isCustomized: true
        };
      }
      return r;
    });
    onSaveWeekRows(currentWeek, newRows);
  };

  const handleAddRow = () => {
    const newRow: LessonPlanRow = {
      id: `custom-row-${Date.now()}`,
      dayOfWeek: 2,
      dateStr: weekDates.startDate,
      session: 'Sáng',
      period: 1,
      className: '3A1',
      subject: 'Tin học',
      lessonName: 'Tiết học bổ sung',
      integrationNote: '',
      isCustomized: true
    };
    onSaveWeekRows(currentWeek, [...displayRows, newRow]);
    showToast('Đã thêm 1 dòng mới vào kế hoạch dạy học!');
  };

  const handleDeleteRow = (id: string) => {
    if (window.confirm('Bạn có chắc chắn muốn xóa dòng tiết học này không?')) {
      const newRows = displayRows.filter((r) => r.id !== id);
      onSaveWeekRows(currentWeek, newRows);
      showToast('Đã xóa dòng tiết học!');
    }
  };

  const handleResetToDefault = () => {
    if (window.confirm(`Khôi phục kế hoạch tuần ${currentWeek} về nguyên bản từ Thời khóa biểu và PPCT?`)) {
      onResetWeekRows(currentWeek);
      showToast(`Đã khôi phục kế hoạch tuần ${currentWeek}!`);
    }
  };

  const handleExportDocx = async () => {
    try {
      setIsExporting(true);
      await exportLessonPlanToDocx(
        config,
        currentWeek,
        weekDates.startDate,
        weekDates.endDate,
        sortedDisplayRows,
        teacherType
      );
      showToast(`Xuất file Word Tuần ${currentWeek} thành công!`);
    } catch (err) {
      console.error('Lỗi khi xuất Word:', err);
      alert('Có lỗi xảy ra khi tạo file Word. Vui lòng thử lại.');
    } finally {
      setIsExporting(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Toast notification */}
      {toastMessage && (
        <div className="fixed top-5 right-5 z-50 bg-teal-800 text-white text-xs font-black px-4 py-2.5 rounded-2xl shadow-xl border border-teal-600 flex items-center gap-2 animate-in slide-in-from-top duration-200">
          <Sparkles className="w-4 h-4 text-emerald-300" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Control Bar: Chọn tuần, chuyển tuần, các nút hành động */}
      <div className="bg-white/95 backdrop-blur-md rounded-3xl p-4 sm:p-5 border-2 border-teal-200/80 shadow-lg shadow-teal-900/5 flex flex-col md:flex-row items-center justify-between gap-4">
        {/* Tuần Navigation */}
        <div className="flex items-center gap-3 w-full md:w-auto justify-between md:justify-start">
          <div className="flex items-center gap-1.5">
            <button
              type="button"
              disabled={currentWeek <= 1}
              onClick={() => setCurrentWeek((w) => Math.max(1, w - 1))}
              className="p-2 rounded-xl bg-teal-50 hover:bg-teal-100 text-teal-700 disabled:opacity-40 disabled:cursor-not-allowed transition-all cursor-pointer"
              title="Tuần trước"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-2 px-3 py-1.5 rounded-2xl bg-teal-50/80 border border-teal-200">
              <Calendar className="w-4 h-4 text-teal-600" />
              <span className="text-xs font-bold text-slate-600">Tuần:</span>
              <select
                value={currentWeek}
                onChange={(e) => setCurrentWeek(Number(e.target.value))}
                className="bg-transparent font-black text-teal-800 text-sm focus:outline-none cursor-pointer"
              >
                {Array.from({ length: 35 }, (_, i) => i + 1).map((w) => (
                  <option key={w} value={w}>
                    Tuần {w}
                  </option>
                ))}
              </select>
            </div>

            <button
              type="button"
              disabled={currentWeek >= 35}
              onClick={() => setCurrentWeek((w) => Math.min(35, w + 1))}
              className="p-2 rounded-xl bg-teal-50 hover:bg-teal-100 text-teal-700 disabled:opacity-40 disabled:cursor-not-allowed transition-all cursor-pointer"
              title="Tuần kế tiếp"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

          <div className="text-left space-y-0.5">
            <div className="flex items-center gap-1.5 flex-wrap">
              <span className="text-xs font-black text-slate-800">
                Từ {weekDates.startDate} đến {weekDates.endDate}
              </span>
              <button
                type="button"
                onClick={handleOpenWeekDateModal}
                className="px-2 py-0.5 rounded-lg bg-teal-50 hover:bg-teal-100 text-teal-800 border border-teal-200 text-[10px] font-bold flex items-center gap-1 cursor-pointer transition-colors"
                title="Tùy chỉnh ngày bắt đầu cho tuần này (VD: sau khi nghỉ Tết)"
              >
                <Edit2 className="w-3 h-3 text-teal-600" />
                <span>Nghỉ Tết / Sửa ngày tuần</span>
              </button>
            </div>

            <div className="flex items-center gap-2 text-[11px] text-slate-500 font-medium">
              <span>Tổng số: {displayRows.length} tiết dạy</span>
              {hasDirectOverride && (
                <span className="text-[10px] font-black px-1.5 py-0.2 rounded bg-amber-100 text-amber-800 border border-amber-200">
                  ✨ Mốc đổi ngày Tuần {currentWeek}
                </span>
              )}
              {!hasDirectOverride && inheritedBaseWeek && (
                <span className="text-[10px] font-bold px-1.5 py-0.2 rounded bg-teal-50 text-teal-700 border border-teal-200">
                  🔗 Tự động nối tiếp từ Tuần {inheritedBaseWeek}
                </span>
              )}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-2 w-full md:w-auto justify-end">
          {/* Thay đổi cỡ chữ hiển thị */}
          <div className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-100 border border-slate-200 text-xs font-bold text-slate-700">
            <span>Cỡ chữ:</span>
            <select
              value={displayFontSize}
              onChange={(e) => setDisplayFontSize(Number(e.target.value))}
              className="bg-transparent font-black text-teal-800 text-xs focus:outline-none cursor-pointer"
            >
              <option value={11}>11 px</option>
              <option value={12}>12 px (Chuẩn)</option>
              <option value={13}>13 px</option>
              <option value={14}>14 px</option>
              <option value={15}>15 px</option>
              <option value={16}>16 px</option>
            </select>
          </div>

          <button
            type="button"
            onClick={handleAddRow}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold bg-teal-50 text-teal-700 hover:bg-teal-100 border border-teal-200 transition-all cursor-pointer"
            title="Thêm 1 dòng tiết học thủ công"
          >
            <Plus className="w-4 h-4" />
            <span>Thêm dòng</span>
          </button>

          <div
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-black bg-emerald-50 text-emerald-800 border border-emerald-300 shadow-2xs select-none"
            title="Hệ thống tự động đồng bộ 100% thời khóa biểu & bài dạy PPCT thời gian thực"
          >
            <Sparkles className="w-3.5 h-3.5 text-emerald-600 animate-pulse" />
            <span>Tự động đồng bộ PPCT & TKB</span>
          </div>

          <button
            type="button"
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold bg-slate-100 text-slate-700 hover:bg-slate-200 transition-all cursor-pointer"
            title="In văn bản"
          >
            <Printer className="w-4 h-4" />
            <span>In</span>
          </button>

          <button
            type="button"
            disabled={isExporting}
            onClick={handleExportDocx}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-black bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white shadow-md shadow-teal-600/25 transition-all cursor-pointer disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            <span>{isExporting ? 'Đang xuất...' : 'Xuất Word (cỡ 12)'}</span>
          </button>
        </div>
      </div>

      {/* Main Document Layout - Styled like standard A4 paper with auto-scaling */}
      <div className="a4-paper-frame p-6 sm:p-10 font-serif text-slate-900 my-4">
        {/* Document Header (Trường & Tổ chuyên môn bên trái, Quốc hiệu & Tiêu ngữ bên phải nằm trong cùng 1 hàng) */}
        <div className="grid grid-cols-2 gap-4 text-center mb-6">
          <div className="flex flex-col items-center justify-start min-w-0">
            <p className="text-xs sm:text-sm font-normal text-slate-900 uppercase tracking-tight whitespace-nowrap overflow-hidden text-ellipsis max-w-full">
              {config.schoolName || 'TRƯỜNG TIỂU HỌC THẠNH YÊN 1'}
            </p>
            <div className="relative inline-block mt-0.5 max-w-full">
              <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight pb-0.5 whitespace-nowrap overflow-hidden text-ellipsis">
                {config.departmentName || 'TỔ CHUYÊN MÔN 4+5'}
              </p>
              <div className="w-full h-[1.5px] bg-slate-900 mx-auto" />
            </div>
          </div>
          <div className="flex flex-col items-center justify-start min-w-0">
            <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight whitespace-nowrap overflow-hidden text-ellipsis max-w-full">
              {config.republicTitleTop || 'CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM'}
            </p>
            <div className="relative inline-block mt-0.5 max-w-full">
              <p className="text-xs sm:text-sm font-bold text-slate-900 pb-0.5 whitespace-nowrap overflow-hidden text-ellipsis">
                {config.republicTitleSub || 'Độc lập – Tự do – Hạnh phúc'}
              </p>
              <div className="w-full h-[1.5px] bg-slate-900 mx-auto" />
            </div>
          </div>
        </div>

        {/* Title */}
        <div className="text-center my-5 space-y-1">
          <h2 className="text-lg sm:text-xl font-bold text-slate-900 uppercase tracking-tight">
            {teacherType === 'GVCN'
              ? `LỊCH BÁO GIẢNG LỚP ${homeClassName.toUpperCase()}`
              : (config.documentTitle || 'KẾ HOẠCH DẠY HỌC')}
          </h2>
          {teacherType === 'GVCN' ? (
            config.subjectTitle &&
            config.subjectTitle !== 'DÀNH CHO GIÁO VIÊN CHỦ NHIỆM' &&
            config.subjectTitle !== 'MÔN: TIN HỌC - CÔNG NGHỆ' ? (
              <h3 className="text-sm sm:text-base font-bold text-slate-900 uppercase tracking-tight">
                {config.subjectTitle}
              </h3>
            ) : null
          ) : (
            <h3 className="text-sm sm:text-base font-bold text-slate-900 uppercase tracking-tight">
              {config.subjectTitle || 'MÔN: TIN HỌC - CÔNG NGHỆ'}
            </h3>
          )}
          <p className="text-xs sm:text-sm italic text-slate-800">
            Tuần {currentWeek} thực hiện từ ngày {weekDates.startDate} đến ngày {weekDates.endDate}
          </p>
        </div>

        {/* Table of Lessons matching attached PDF */}
        <div className="overflow-x-auto my-4">
          <table
            style={{ fontSize: `${displayFontSize}px` }}
            className="w-full border-collapse border border-black text-slate-900"
          >
            <thead>
              <tr className="bg-white text-slate-900 text-center font-bold uppercase">
                <th className={`px-2 border border-black w-24 align-middle ${dynamicCellPy}`}>THỨ</th>
                <th className={`px-2 border border-black w-18 align-middle ${dynamicCellPy}`}>BUỔI</th>
                <th className={`px-2 border border-black w-12 align-middle ${dynamicCellPy}`}>TIẾT</th>
                {teacherType !== 'GVCN' && (
                  <th className={`px-2 border border-black w-16 align-middle ${dynamicCellPy}`}>LỚP</th>
                )}
                <th className={`px-2 border border-black w-28 align-middle ${dynamicCellPy}`}>MÔN HỌC</th>
                {teacherType === 'GVCN' && (
                  <th className={`px-2 border border-black w-32 align-middle ${dynamicCellPy}`}>PHÂN MÔN</th>
                )}
                <th className={`px-3 border border-black min-w-[220px] align-middle ${dynamicCellPy}`}>TÊN BÀI DẠY</th>
                <th className={`px-2 border border-black min-w-[150px] align-middle text-center ${dynamicCellPy}`}>
                  <div className="leading-tight">ĐIỀU CHỈNH/</div>
                  <div className="leading-tight">TÍCH HỢP</div>
                </th>
                <th className={`px-1 border border-black w-14 print:hidden align-middle ${dynamicCellPy}`}>TÁC VỤ</th>
              </tr>
            </thead>
            <tbody>
              {rowSpanData.length === 0 ? (
                // Nếu chưa có dữ liệu, hiển thị khung bảng chuẩn
                Array.from({ length: 6 }).map((_, i) => (
                  <tr key={`empty-${i}`} className="h-8">
                    {i === 0 && (
                      <td rowSpan={6} className="border border-black text-center align-middle font-bold text-slate-400">
                        (Chưa có tiết dạy)
                      </td>
                    )}
                    {i === 0 && (
                      <td rowSpan={3} className="border border-black text-center align-middle font-bold text-slate-400">
                        Sáng
                      </td>
                    )}
                    {i === 3 && (
                      <td rowSpan={3} className="border border-black text-center align-middle font-bold text-slate-400">
                        Chiều
                      </td>
                    )}
                    <td className="border border-black text-center text-slate-400">{(i % 3) + 1}</td>
                    {teacherType !== 'GVCN' && <td className="border border-black"></td>}
                    <td className="border border-black"></td>
                    {teacherType === 'GVCN' && <td className="border border-black"></td>}
                    <td className="border border-black"></td>
                    <td className="border border-black"></td>
                    <td className="border border-black print:hidden"></td>
                  </tr>
                ))
              ) : (
                rowSpanData.map(({ row, daySpan, sessionSpan, subjectSpan }, idx) => (
                  <tr key={row.id || idx} className="hover:bg-amber-50/30 transition-colors group">
                    {/* THỨ (Gom ô cho toàn bộ các tiết trong ngày) */}
                    {daySpan > 0 && (
                      <td
                        rowSpan={daySpan}
                        className={`px-2 text-center border border-black font-bold align-middle bg-white text-slate-900 ${dynamicCellPy}`}
                      >
                        <div className="font-bold whitespace-nowrap">{getDayOfWeekName(row.dayOfWeek)}</div>
                        <div className="text-[10px] text-slate-500 font-normal">({row.dateStr})</div>
                      </td>
                    )}

                    {/* BUỔI (Gom ô cho toàn bộ các tiết trong buổi của ngày) */}
                    {sessionSpan > 0 && (
                      <td
                        rowSpan={sessionSpan}
                        className={`px-2 text-center border border-black font-bold align-middle bg-white text-slate-900 ${dynamicCellPy}`}
                      >
                        {row.session}
                      </td>
                    )}

                    {/* TIẾT */}
                    <td className={`px-1 text-center border border-black font-bold align-middle ${dynamicCellPy}`}>
                      {row.period}
                    </td>

                    {/* LỚP (Chỉ hiển thị với Giáo viên bộ môn) */}
                    {teacherType !== 'GVCN' && (
                      <td className={`px-2 text-center border border-black font-bold align-middle ${dynamicCellPy}`}>
                        {row.className}
                      </td>
                    )}

                    {/* MÔN HỌC (Tự động gộp ô nếu có nhiều phân môn) */}
                    {teacherType === 'GVCN' ? (
                      subjectSpan > 0 && (
                        <td
                          rowSpan={subjectSpan}
                          className={`px-2 text-center border border-black font-bold align-middle bg-white text-slate-900 ${dynamicCellPy}`}
                        >
                          {getPureSubject(row.subject)}
                        </td>
                      )
                    ) : (
                      <td className={`px-2 text-center border border-black align-middle ${dynamicCellPy}`}>
                        {row.subject}
                      </td>
                    )}

                    {/* PHÂN MÔN (Dành cho GVCN) */}
                    {teacherType === 'GVCN' && (
                      <td className={`px-2 text-center border border-black align-middle font-medium ${dynamicCellPy}`}>
                        <input
                          type="text"
                          value={row.subSubject || ''}
                          onChange={(e) => handleInlineChange(row.id, 'subSubject', e.target.value)}
                          placeholder="-"
                          className="w-full text-center bg-transparent hover:bg-slate-50 focus:bg-white px-1 py-0.5 rounded border border-transparent hover:border-slate-300 focus:border-teal-500 focus:outline-none transition-all font-bold text-teal-950"
                        />
                      </td>
                    )}

                    {/* TÊN BÀI DẠY */}
                    <td className={`px-2 text-left border border-black align-middle font-medium ${dynamicCellPy}`}>
                      <input
                        type="text"
                        value={row.lessonName}
                        onChange={(e) => handleInlineChange(row.id, 'lessonName', e.target.value)}
                        className="w-full bg-transparent hover:bg-slate-50 focus:bg-white px-1.5 py-0.5 rounded border border-transparent hover:border-slate-300 focus:border-teal-500 focus:outline-none transition-all"
                      />
                    </td>

                    {/* ĐIỀU CHỈNH/ TÍCH HỢP */}
                    <td className={`px-2 text-left border border-black align-middle ${dynamicCellPy}`}>
                      <input
                        type="text"
                        value={row.integrationNote || ''}
                        placeholder="..."
                        onChange={(e) => handleInlineChange(row.id, 'integrationNote', e.target.value)}
                        className="w-full bg-transparent hover:bg-slate-50 focus:bg-white px-1.5 py-0.5 rounded border border-transparent hover:border-slate-300 focus:border-teal-500 focus:outline-none transition-all"
                      />
                    </td>

                    {/* TÁC VỤ */}
                    <td className="py-1 px-1 text-center border border-black print:hidden align-middle">
                      <div className="flex items-center justify-center gap-1 opacity-60 group-hover:opacity-100 transition-opacity">
                        <button
                          type="button"
                          onClick={() => setEditingRow(row)}
                          className="p-1 rounded text-teal-700 hover:bg-teal-50 cursor-pointer"
                          title="Chỉnh sửa chi tiết"
                        >
                          <Edit2 className="w-3.5 h-3.5" />
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDeleteRow(row.id)}
                          className="p-1 rounded text-rose-600 hover:bg-rose-50 cursor-pointer"
                          title="Xóa dòng"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Footer Signatures matching attached PDF:
            Date on right, then 3 columns: DUYỆT CỦA P.HIỆU TRƯỜNG | TỔ TRƯỜNG | GIÁO VIÊN */}
        <div className="mt-8 pt-4 w-full">
          {/* Dòng ngày tháng địa điểm nằm phía trên bên phải, căn lề phải chuẩn A4 */}
          <div className="w-full flex justify-end mb-2 pr-4 sm:pr-8">
            <p className="text-xs sm:text-sm italic text-slate-900 whitespace-nowrap text-right">
              {config.location || 'Vĩnh Hòa'}, ngày .... tháng .... năm ....
            </p>
          </div>

          {/* Bảng 3 cột chia tỷ lệ hợp lý (38% - 28% - 34%), không bị chồng chữ hay rớt dòng */}
          <table className="w-full border-none border-collapse text-center table-fixed">
            <tbody>
              <tr>
                {/* Cột 1: DUYỆT CỦA P.HIỆU TRƯỜNG */}
                <td className="w-[38%] border-none align-top text-center px-1">
                  <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight whitespace-nowrap overflow-visible">
                    {config.principalTitle || 'DUYỆT CỦA P.HIỆU TRƯỜNG'}
                  </p>
                  <div className="h-20 sm:h-24 flex items-center justify-center">
                    {/* Khoảng trống ký tên & đóng dấu */}
                  </div>
                  <p className="text-xs sm:text-sm font-bold text-slate-900 whitespace-nowrap">
                    {config.principalName || ''}
                  </p>
                </td>

                {/* Cột 2: TỔ TRƯỜNG */}
                <td className="w-[28%] border-none align-top text-center px-1">
                  <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight whitespace-nowrap overflow-visible">
                    {config.headTeacherTitle || 'TỔ TRƯỜNG'}
                  </p>
                  <div className="h-20 sm:h-24 flex items-center justify-center">
                    {/* Khoảng trống ký tên */}
                  </div>
                  <p className="text-xs sm:text-sm font-bold text-slate-900 whitespace-nowrap">
                    {config.headTeacherName || ''}
                  </p>
                </td>

                {/* Cột 3: GIÁO VIÊN */}
                <td className="w-[34%] border-none align-top text-center px-1">
                  <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight whitespace-nowrap overflow-visible">
                    {config.teacherTitle || 'GIÁO VIÊN'}
                  </p>
                  <div className="h-20 sm:h-24 flex items-center justify-center">
                    {/* Khoảng trống ký tên */}
                  </div>
                  <p className="text-xs sm:text-sm font-bold text-slate-900 whitespace-nowrap">
                    {config.teacherName || 'Nguyễn Thành Luân'}
                  </p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal chỉnh sửa chi tiết */}
      <LessonDetailModal
        isOpen={Boolean(editingRow)}
        lesson={editingRow}
        onClose={() => setEditingRow(null)}
        onSave={handleUpdateRow}
      />

      {/* Modal Tùy chỉnh mốc ngày bắt đầu tuần (VD: Nghỉ Tết) */}
      {isWeekDateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
          <div className="bg-white rounded-3xl max-w-md w-full p-6 shadow-2xl border-2 border-teal-200 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <div className="flex items-center gap-2">
                <div className="w-9 h-9 rounded-2xl bg-teal-50 border border-teal-200 text-teal-700 flex items-center justify-center font-bold">
                  <Calendar className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-base font-black text-slate-800">
                    Mốc Ngày Bắt Đầu Tuần {currentWeek}
                  </h3>
                  <p className="text-[11px] font-semibold text-slate-500">
                    Cấu hình lịch nghỉ Tết / Nghỉ lễ kéo dài
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setIsWeekDateModalOpen(false)}
                className="p-1 rounded-xl text-slate-400 hover:bg-slate-100"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleSaveWeekDateOverride} className="space-y-4">
              <div className="p-3 rounded-2xl bg-teal-50/70 border border-teal-200/80 text-xs text-teal-900 leading-relaxed">
                <p className="font-bold mb-1">💡 Quy tắc tự động nối tiếp liền kề:</p>
                <p>
                  Khi Thầy/Cô thiết lập ngày bắt đầu (Thứ Hai) cho <span className="font-extrabold text-teal-800">Tuần {currentWeek}</span> (ví dụ: ngày đi học lại sau nghỉ Tết), tất cả các tuần tiếp theo (<span className="font-semibold text-teal-800">Tuần {currentWeek + 1}, Tuần {currentWeek + 2}...</span>) sẽ tự động tính nối tiếp liên tục theo mốc mới này!
                </p>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1.5">
                  Ngày Thứ Hai bắt đầu Tuần {currentWeek}:
                </label>
                <input
                  type="date"
                  value={overrideDateInput}
                  onChange={(e) => setOverrideDateInput(e.target.value)}
                  className="w-full px-3 py-2.5 rounded-xl border border-slate-300 text-sm font-bold text-slate-800 focus:outline-none focus:border-teal-500"
                  required
                />
              </div>

              {/* Danh sách mốc tùy chỉnh đang có */}
              {config.weekStartOverrides && Object.keys(config.weekStartOverrides).length > 0 && (
                <div className="pt-2 border-t border-slate-100">
                  <span className="text-[11px] font-bold text-slate-400 block mb-1">
                    Các mốc tùy chỉnh đã tạo:
                  </span>
                  <div className="flex flex-wrap gap-1.5 max-h-24 overflow-y-auto">
                    {Object.entries(config.weekStartOverrides).map(([wNum, wDate]) => (
                      <span
                        key={wNum}
                        className={`text-[10px] font-bold px-2 py-1 rounded-lg border ${
                          Number(wNum) === currentWeek
                            ? 'bg-amber-100 text-amber-900 border-amber-300'
                            : 'bg-slate-100 text-slate-700 border-slate-200'
                        }`}
                      >
                        Tuần {wNum}: {wDate}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              <div className="flex items-center justify-between gap-2 pt-3 border-t border-slate-100">
                {hasDirectOverride ? (
                  <button
                    type="button"
                    onClick={handleClearWeekDateOverride}
                    className="px-3 py-2 rounded-xl text-xs font-bold text-rose-600 bg-rose-50 hover:bg-rose-100 border border-rose-200 cursor-pointer"
                  >
                    Xóa tùy chỉnh
                  </button>
                ) : (
                  <span />
                )}

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setIsWeekDateModalOpen(false)}
                    className="px-3.5 py-2 rounded-xl text-xs font-bold text-slate-600 bg-slate-100 hover:bg-slate-200 cursor-pointer"
                  >
                    Hủy
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 rounded-xl text-xs font-black text-white bg-teal-600 hover:bg-teal-700 shadow-md shadow-teal-600/20 cursor-pointer"
                  >
                    Lưu mốc tuần
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
